Selenium exercises 1 to 13 - Completed (V1)
infuse-training-aug-2024/Practice-Vineet pull request #4
Opened 2024-09-17 11:58 UTC by Vineet-Sawant

2024-09-19 08:53 UTC, niiishaaant requested changes
Modularise the code so that it is readable and reusable.
Use OOP concepts.
Use proper naming throughout the exercises.

2024-09-19 08:53 UTC, nshnt-xyz commented on selenium-exercise/1-chrome.py
> +
You can create a class that initialises the drivers and then use it for all the exercises.

2024-09-19 08:53 UTC, nshnt-xyz commented on selenium-exercise/1-chrome.py
> +sleep(2)
Don't use sleep.

2024-09-19 08:53 UTC, nshnt-xyz commented on selenium-exercise/2.py
> +    assert title
Is assert needed here?

2024-09-19 08:53 UTC, nshnt-xyz commented on selenium-exercise/4.py
> +    radio_btn = driver.find_element(By.CSS_SELECTOR, value='#basicBootstrapForm > div:nth-child(5) > div > label:nth-child(1) > input')
Use variables to store identifiers before using them in methods. This applies to all exercises.

2024-09-19 08:53 UTC, niiishaaant commented on selenium-exercise/4.py
> +    check_box_1 = driver.find_element(By.ID, value="checkbox2")
Use methods to do operations. This applies to all exercises.

2024-09-19 08:53 UTC, niiishaaant commented on selenium-exercise/5.py
> +    sleep(2)
Don't use sleeps.

2024-09-19 08:53 UTC, niiishaaant commented on selenium-exercise/7.py
> +        chrome_service = ChromeService(executable_path=driver_path)
This function is doing quite a lot of things, modularise it so its more readable.

2024-09-19 08:53 UTC, niiishaaant commented on selenium-exercise/8.py
> +    iframe = driver.find_element(By.XPATH, value='/html/body/div[1]/div[1]/div[2]/div/div/div[2]/div/div/div[3]/p/iframe')
See if you can use anything other than XPATH.

2024-09-19 08:53 UTC, niiishaaant commented on selenium-exercise/8.py
> +    action.click_and_hold(handler).move_by_offset(100, 0).release().perform()
You can click on the slider button and then use arrow keys to do this. It'll be much cleaner.

2024-09-19 08:53 UTC, niiishaaant commented on selenium-exercise/12.py
> +    #     dropdown = driver.find_element(By.CLASS_NAME, 'product_sort_container')
Remove commented out code.

2024-09-19 08:53 UTC, niiishaaant commented on selenium-exercise/13.py
> +def chrome_setUp():
This isnt the right way to name methods, python uses snake case.

2024-09-21 07:19 UTC, Vineet-Sawant commented on selenium-exercise/1-chrome.py
> +
Done ✅

2024-09-21 07:20 UTC, Vineet-Sawant commented on selenium-exercise/1-chrome.py
> +sleep(2)
Done ✅

2024-09-21 07:23 UTC, Vineet-Sawant commented on selenium-exercise/2.py
> +    assert title
Done ✅

2024-09-21 07:42 UTC, Vineet-Sawant commented on selenium-exercise/4.py
> +    radio_btn = driver.find_element(By.CSS_SELECTOR, value='#basicBootstrapForm > div:nth-child(5) > div > label:nth-child(1) > input')
Done ✅

2024-09-21 07:48 UTC, Vineet-Sawant commented on selenium-exercise/5.py
> +    sleep(2)
Done ✅

2024-09-25 04:42 UTC, merged